import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef } from "react";
import { useForm, type FieldValues, type SubmitHandler } from "react-hook-form";
import toast from "react-hot-toast";
import { api } from "~/utils/api";

const formatPoemFromDB = (poem: string): string => {
  // Helper method to format poem from DB
  const separatorMap: Record<string, string> = {
    ",": ",+",
    ".": ".+",
    "?": "?+",
  };
  const separatorReplacedPoem = poem.replace(
    /[,.?]/g,
    (s) => separatorMap[s] || s
  );

  const stringToArray = separatorReplacedPoem.split("+");
  const formattedArray = stringToArray.map((s, i) => {
    if ((i + 1) % 4 === 0) {
      return `${s}<br/><br/>`;
    } else if (i !== stringToArray.length - 1) {
      return `${s}<br/>`;
    }
    return s;
  });

  return formattedArray.join("");
};

const BackgroundMusic = () => {
  const audioRef = useRef<HTMLAudioElement>(null);

  useEffect(() => {
    if (audioRef.current) {
      audioRef.current.play().catch((error) => {
        // Handle play error, if any
        console.error("Audio play error:", error);
      });
      audioRef.current.loop = true;
    }
  });

  return <audio ref={audioRef} src="/music/ambien.mp3" loop />;
};

const HiddenContent = (props: { content: string }) => {
  return (
    <>
      <BackgroundMusic />
      <div className="animate-fade-in-slow rounded-lg bg-custom-div px-10 py-10 text-custom-content">
        {props.content ? (
          <>
            <h1 className="text-4xl">Monthly Poetry</h1>
            <br />
            <br />
            <p
              className="text-xl"
              dangerouslySetInnerHTML={{
                __html: formatPoemFromDB(props.content),
              }}
            />
          </>
        ) : (
          <div>
            <span className="text-xl text-red-500">Something went wrong!</span>
          </div>
        )}
      </div>
    </>
  );
};

const Home: NextPage = () => {
  const { register, handleSubmit, reset } = useForm();

  const { data, mutate } = api.poetry.viewContent.useMutation({
    onError: (e) => {
      console.error(e);
      toast.error("Unauthorized!");
    },
  });

  const submitPass = (input: { password: string }) => {
    reset();
    mutate({ contentPass: input.password });
  };

  return (
    <>
      <Head>
        <title>Poetree</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main
        className={`flex h-screen items-center justify-center bg-cover bg-center duration-10s ease-in-out ${
          data ? "bg-aman" : "bg-amanGray"
        }`}
      >
        {!data ? (
          <form
            onSubmit={handleSubmit(submitPass as SubmitHandler<FieldValues>)}
          >
            <div className="flex flex-col space-y-4 text-xl">
              <label>
                <input
                  className="text-center"
                  placeholder="Password"
                  type="password"
                  {...register("password")}
                />
              </label>
              <button
                type="submit"
                className="rounded-sm bg-custom-div text-custom-content"
              >
                Submit
              </button>
            </div>
          </form>
        ) : (
          <HiddenContent content={data.content} />
        )}
      </main>
    </>
  );
};

export default Home;
